// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amlhmlfzvqdghbbuluio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbGhtbGZ6dnFkZ2hiYnVsdWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxOTE5OTAsImV4cCI6MjA4OTc2Nzk5MH0.S24EARHHjO9n3eWJMNT--18jyd5dGGHqBDtk58uq608";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});